### ISSUE TITLE
Convert an arbitrary Data Frame to Succinct Data Frame

### ISSUE THREAD

**Issue by kant111** [amplab/succinct#33]
Right now, To convert an Arbitrary Data Frame to Succinct Data Frame I would need to write to a File and then read it back from a file as follows

val df = spark.sql("SELECT * from table_name limit 100") //Cassandra Query
df.write.format("edu.berkeley.cs.succinct.sql").save("/path/to/data")
val succinctCities = sqlContext.succinctTable("/path/to/data")

It would be great to have a functionality where it is easy to convert any arbitrary data frame to succinct data frame using a single method call if possible.

@anuragkh

**Comment by anuragkh** [comment]
Fixed in 126dce55c4a248335e16cb69760a954ed095ab00.

If you want to directly convert a DataFrame to Succinct format, you can do the following:

import edu.berkeley.cs.succinct.sql._
val df = spark.sql("SELECT * from table_name limit 100") //Cassandra Query
val succinctDf = df.toSuccinctDF

Thanks!
Anurag
